# station_id: rpi5-a        # opcional; se usa sólo si falta la variable de entorno STATION_ID
sample_rate_hz: 10
scan_block_size: 50         # bloque de 5 s -> timeout dinámico = 5 s + 0.5 s de margen
channels:
  - ch: 0
    sensor: LVDT_P1
    unit: mm
    v_range: 10             # ±10 V en MCC128
    calib: {gain: 2.000, offset: -0.10}   # mm = gain*V + offset
  - ch: 1
    sensor: LVDT_P2
    unit: mm
    v_range: 10
    calib: {gain: 2.000, offset: 0.00}
