station_id: rpi5-a
sample_rate_hz: 10
scan_block_size: 50         # bloques de 5 s para respetar timeout de read_block
channels:
  - ch: 0
    sensor: LVDT_P1
    unit: mm
    v_range: 10             # ±10 V en MCC128
    calib: {gain: 2.000, offset: -0.10}   # mm = gain*V + offset
  - ch: 1
    sensor: LVDT_P2
    unit: mm
    v_range: 10
    calib: {gain: 2.000, offset: 0.00}
