station_id: rpi5-a
acquisition:
  sample_rate_hz: 10
  block_size: 50
  duration_s:
  drift_detection:
    correction_threshold_ns: 2000000
channels:
  - index: 0
    name: LVDT_P1
    unit: mm
    voltage_range: 10.0
    calibration:
      gain: 2.0
      offset: -0.1
  - index: 1
    name: LVDT_P2
    unit: mm
    voltage_range: 10.0
    calibration:
      gain: 2.0
      offset: 0.0
